name: cabal-toolkit
version: 0.0.7
category: Distribution
synopsis: Helper functions for writing custom Setup.hs scripts.
description: |
  Helper functions for writing custom Setup.hs scripts.
  .
  This is useful to access configuration parameters of a @Cabal@-based project
  at runtime, e.g. when you want to supply the right
  @GHC_PACKAGE_PATH@ to @ghc@ oder @ghci@.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/cabal-toolkit

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - binary
  - bytestring
  - containers
  - Cabal >= 1.24 && < 4
  - ghc
  - template-haskell

library:
  source-dirs: src
  other-extensions:
    - TemplateHaskell
