version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:haskell
    steps:
      - checkout
      - run: |
          stack --nix --no-terminal build --haddock
          stack --nix --no-terminal build --haddock --stack-yaml=stack-lts-9.yaml
