version: 2
jobs:
  build:
    docker:
      - image: terrorjack/rakuen:nightly-2017-11-09
    steps:
      - checkout
      - run: stack --no-terminal build --haddock
      - run: stack --no-terminal --install-ghc build --haddock --stack-yaml=stack-lts-9.yaml
